### ISSUE TITLE
Doesn't work on raspberry pi

### ISSUE THREAD

**Issue by adv0r** [ConsenSys/icebox#1]
tested on model b, default browser

**Comment by kumavis** [comment]
afaik its iOS only atm bc of the external `workflow` dependency (for generating and parsing qr codes). I intend to fix that when i get a moment. ( eg couple weeks from now )

**Comment by hairychris** [comment]
Works fine on raspberry pi running raspbian Jessie and chromium nowadays. Vote to close.

**Comment by christianlundkvist** [comment]
@adv0r Icebox doesn't work on the default browser since the Javascript support on that browser is very limited. I also don't have one to test. 

@hairychris This is great! I thought it would work with Chromium on the RPi and this confirms it, thanks!

@kumavis It's not iOS only, you can pull data on-and-off the offline computer using a USB stick.

Closing...
